# Generated by Django 6.0.2 on 2026-04-14 13:19

import django.db.models.deletion
import django.utils.timezone
import web.models.character
import web.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "photo",
                    models.ImageField(upload_to=web.models.character.photo_upload_to),
                ),
                ("profile", models.TextField(max_length=100000)),
                ("opening_message", models.TextField(blank=True, default="")),
                ("opening_message_input_tokens", models.IntegerField(default=0)),
                ("opening_message_output_tokens", models.IntegerField(default=0)),
                ("opening_message_total_tokens", models.IntegerField(default=0)),
                (
                    "background_image",
                    models.ImageField(
                        upload_to=web.models.character.background_image_upload_to
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("order_number", models.IntegerField(default=0)),
                ("prompt", models.TextField(max_length=10000)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "character_photo",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("character_profile", models.TextField(blank=True, default="")),
                ("character_opening_message", models.TextField(blank=True, default="")),
                (
                    "memory",
                    models.TextField(
                        blank=True, default="", max_length=5000, null=True
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="friends",
                        to="web.character",
                    ),
                ),
            ],
            options={
                "ordering": ["-update_time"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_name", models.CharField(default="新的对话", max_length=100)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="web.friend",
                    ),
                ),
            ],
            options={
                "ordering": ["-update_time"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField(max_length=500)),
                ("input", models.TextField(max_length=10000)),
                ("output", models.TextField(max_length=500)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="web.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        default="user/photos/default.png",
                        upload_to=web.models.user.photo_upload_to,
                    ),
                ),
                ("profile", models.TextField(default="谢谢你的关注", max_length=500)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="friend",
            name="me",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.userprofile"
            ),
        ),
    ]
