# Generated by Django 6.0.2 on 2026-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="author_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="friend",
            name="author_photo",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="friend",
            name="author_username",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="friend",
            name="character_background_image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
