# Generated by Django 6.0.2 on 2026-04-15 13:30

import web.models.character
import web.models.user
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_friend_author_id_friend_author_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="author_photo",
            field=models.ImageField(
                blank=True,
                default="",
                max_length=500,
                upload_to=web.models.user.photo_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="friend",
            name="character_background_image",
            field=models.ImageField(
                blank=True,
                default="",
                max_length=500,
                upload_to=web.models.character.background_image_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="friend",
            name="character_photo",
            field=models.ImageField(
                blank=True,
                default="",
                max_length=500,
                upload_to=web.models.character.photo_upload_to,
            ),
        ),
    ]
