# Generated by Django 6.0.2 on 2026-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_message_total_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="input",
            field=models.TextField(max_length=10000),
        ),
    ]
