# Generated by Django 6.0.2 on 2026-04-02 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_alter_message_input"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="input_token",
            new_name="input_tokens",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="output_token",
            new_name="output_tokens",
        ),
    ]
