# Generated by Django 6.0.2 on 2026-04-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_rename_prompts_systemprompt_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="opening_message",
            field=models.TextField(default=""),
        ),
    ]
