# Generated by Django 6.0.2 on 2026-04-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_character_opening_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="opening_message_input_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="opening_message_output_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="opening_message_total_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
